language: java
sudo: false
install: true
before_install:
- chmod +x mvnw
jdk:
- oraclejdk8
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
notifications:
  email: false
addons:
  sonarcloud:
    token:
      secure: KCtYwKYnpk4qy8Xv/FkOUOTvpnPjFxl6w5tK4WYkMgg8geMLVEuXmQMo3lkZ92ysQKAcLbYsa9ix3q1a0A5UClNJO57CTbOoswmtsfFhRj+vZwcvkBARTcN1sWF4NrkgniQJD3a9FP2QX/19TuWQNk5ZyR/44fvj0tjZVb7e2IPAV4svpQmwR1X4fKqFIhtlj2ZN9fM8gxs+S1/FkOzQGrssO0VTBA+Ohy32QCTqawqCONKE/gj/tQaXcdg0vX6yRTrR/GJ2yn8C3kHnFKZySYbYcfz269BRhKEzcNBpXJQgTQrTthOBI66K31RdNOsdOrH/2ONt7p1DZCRrgWJZWJ4KHiIBjyoGZo1EacwPun3ovmduT0QL/kSmVZjZfoK5OHZm9SQ126eXU2Rbb9MZwrb2vZABCwFQxqafF2qZQ+hijOvHPVMIhdT1l6hLGIXchNmO1aoxQqaODb0kKvaOzKyE71JLZVwMUmHiug7c8KwnpHOgFgYLhj1fjO0uZnC/2imHdDBS93jjNxVjj6Poh/Tz8/w+fcQQn3golD/JslQg1JijuM11mpy7DEHh2dB90aNiEyOMOuuBrF+WPvgN+Lp8wzAp2vCmRYlQk99RN5+xApzivRqcyNAnkMjAviQsEsAVbyc4ygLhgvPu5JLlwZrTKzbHExUzoANgt44yWxU=
